name: Release Tao extension

on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  auto-release:
    if: github.event.pull_request.merged == true
    name: Automated Tao extension release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: clone the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  #avoid unrelated history error
          token: ${{ secrets.SEMVER_GH_TOKEN }} #bypass branch protection rule

      - name: Configure git user
        #configuring git for runner
        run: |
          git config --global user.name "oat-github-bot"
          git config --global user.email "oat-github-bot@taotesting.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CI_NPM_READ_TOKEN }}

      - name: install and run release tool
        env:
          GITHUB_TOKEN: ${{ secrets.SEMVER_GH_TOKEN }}
        run: |
          npm i -g
          npm i update-notifier
          npm config delete //registry.npmjs.org/:_authToken || true
          taoRelease npmRelease --release-branch master --no-interactive
