name: Release Tao extension

on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  auto-release:
    if: github.event.pull_request.merged == true
    name: Automated Tao extension release
    runs-on: ubuntu-latest
    
    steps:    
      - name: clone the repository
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0  #avoid unrelated history error
          token: ${{ secrets.SEMVER_GH_TOKEN }} #bypass branch protection rule

      - name: Configure git user
        #configuring git for runner
        run: |
          git config --global user.name "oat-github-bot"
          git config --global user.email "oat-github-bot@taotesting.com"                            


      - name: install and run release tool
        env: 
          GITHUB_TOKEN: ${{ secrets.SEMVER_GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.BUILD_NPM_TOKEN }}
        run: |
          npm config set //registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}
          npm i -g
          npm i update-notifier 
          #create tag and release a new version
          taoRelease npmRelease --no-interactive

          #Release branch will be different for each repository, make necessary changes. 